name: VSIX Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.1
          registry-url: https://npm.pkg.github.com/    
      - run: sudo npm install -g npx tfx-cli typescript azure-devops-extension-sdk --force      
      - run: npm install && tsc
        working-directory: pr-inspection-assistant/src
      - run: npx tfx-cli extension create --trace-level debug
        working-directory: pr-inspection-assistant
      - run: gh release upload ${{github.event.release.tag_name}} *.vsix
        working-directory: pr-inspection-assistant
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}